name: publish-release

on:
  push:
    branches:
      - main

jobs:
  pre-release:
    runs-on: ubuntu-latest

    outputs:
      changed: ${{ steps.version-check.outputs.changed }}
      version: ${{ steps.version-check.outputs.version }}

    steps:
      - name: Fetch codebase
        uses: actions/checkout@v4

      - name: Check version
        id: version-check
        uses: EndBug/version-check@v2
        with:
          diff-search: true

  main:
    runs-on: ubuntu-latest
    needs: pre-release
    if: needs.pre-release.outputs.changed == 'true'

    steps:
      - name: Fetch codebase
        uses: actions/checkout@v4

      # - name: Check version
      #   id: version-check
      #   uses: EndBug/version-check@v2
      #   with:
      #     diff-search: true

      - name: Install dependencies
        # if: steps.version-check.outputs.changed == 'true'
        run: yarn install

      - name: Build application
        # if: steps.version-check.outputs.changed == 'true'
        run: yarn build

      - name: Run tests
        # if: steps.version-check.outputs.changed == 'true'
        run: echo "TODO - Add tests"

      - name: Extract release notes
        # if: steps.version-check.outputs.changed == 'true'
        run: |
          VERSION=${{ needs.pre-release.outputs.version }}
          sed -n "/## \[v${VERSION}\]/,/## \[v/p" CHANGELOG.md | sed '1d;$d' > release_notes.txt

          if [ ! -s release_notes.txt ]; then
            echo "No release notes available for v$VERSION" > release_notes.txt
          fi

      - name: Publish release
        # if: steps.version-check.outputs.changed == 'true'
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v${{ needs.pre-release.outputs.version }}
          release_name: v${{ needs.pre-release.outputs.version }}
          body_path: release_notes.txt
