name: Release

on:
  workflow_dispatch:
    inputs:
      version:
        description: "Enter the version tag (e.g., v1.0.0)"
        required: true
        type: string

jobs:
  build_and_release:
    runs-on: ubuntu-latest

    steps:
      - name: checkout repository
        uses: actions/checkout@v4

      - name: install dependencies
        run: yarn install

      - name: build application
        run: yarn build

      # - name: extract changelog
      #   id: extract_changelog
      #   run: |
      #     VERSION=${{ github.event.inputs.version }}

      #     # Extract changelog entry between the given version and the next version or end of file
      #     sed -n "/## \[${VERSION}\]/,/## \[v/p" CHANGELOG.md | sed '1d;$d' > release_notes.txt

      #     # Check if the release notes are empty or not found
      #     if [ ! -s release_notes.txt ]; then
      #       echo "No release notes available for $VERSION." > release_notes.txt
      #     fi

      #     # Display the extracted release notes
      #     cat release_notes.txt

      #     # Set the extracted release notes as an output
      #     echo "::set-output name=notes::$(cat release_notes.txt)"

      - name: create release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.event.inputs.version }}
          release_name: ${{ github.event.inputs.version }}
          body: "hello, world!"
          # body: ${{ steps.extract_changelog.outputs.notes }}
          draft: false
          prerelease: false

      # - name: upload release artifacts
      #   uses: actions/upload-artifact@v4
      #   with:
      #     name: build-artifact
      #     path: build/
