name: Release

on:
  push:
    branches:
      - main
  # workflow_dispatch:
  #   inputs:
  #     version:
  #       description: "Enter the version tag (e.g., v1.0.0)"
  #       required: true
  #       type: string

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: version check
        uses: EndBug/version-check@v2
        id: version-check
        with:
          package: package.json
          diff-search: true

      - name: idk what to name this
        if: steps.version-check.outputs.changed == 'false'
        run: exit 1

      - name: checkout repository
        uses: actions/checkout@v4

      - name: install dependencies
        run: yarn install

      - name: build application
        run: yarn build

      - name: extract changelog
        run: |
          VERSION=${{ steps.version-check.outputs.version }}
          sed -n "/## \[${VERSION}\]/,/## \[v/p" CHANGELOG.md | sed '1d;$d' > release_notes.txt

          if [ ! -s release_notes.txt ]; then
            echo "No release notes available for $VERSION." > release_notes.txt
          fi
      - name: create release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v${{ steps.version-check.outputs.version }}
          release_name: v${{ steps.version-check.outputs.version }}
          body_path: release_notes.txt
