name: Release

on:
  workflow_dispatch:
    inputs:
      version:
        description: "Enter the version tag (e.g., v1.0.0)"
        required: true
        type: string

jobs:
  build_and_release:
    runs-on: ubuntu-latest

    steps:
      - name: checkout repository
        uses: actions/checkout@v3

      - name: install dependencies
        run: yarn install

      - name: build application
        run: yarn build

      - name: extract changelog
        id: extract_changelog
        run: |
          VERSION=${{ github.event.inputs.version }}

          sed -n "/## \[${VERSION}\]/,/## \[v/p" CHANGELOG.md | sed '1d;$d' > release_notes.txt

          if [ ! -s release_notes.txt ]; then
            echo "No release notes available for $VERSION." > release_notes.txt
          fi

          echo "notes=$(cat release_notes.txt)" >> $GITHUB_OUTPUT

      - name: create release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.event.inputs.version }}
          release_name: ${{ github.event.inputs.version }}
          body: ${{ steps.extract_changelog.outputs.notes }}
          draft: false
          prerelease: false

      - name: upload release artifacts
        uses: actions/upload-artifact@v3
        with:
          name: build-artifact
          path: build/
