name: workflows

on:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Fetch codebase
        uses: actions/checkout@v4

      - name: Check version
        id: version-check
        uses: EndBug/version-check@v2
        with:
          diff-search: true

      - name: Install dependencies
        if: steps.version-check.outputs.changed == 'true'
        run: yarn install

      - name: Build application
        if: steps.version-check.outputs.changed == 'true'
        run: yarn build

      - name: Extract release notes
        if: steps.version-check.outputs.changed == 'true'
        run: |
          VERSION=${{ steps.version-check.outputs.version }}
          sed -n "/## \[v${VERSION}\]/,/## \[v/p" CHANGELOG.md | sed '1d;$d' > release_notes.txt || echo "No release notes available v$VERSION" > release_notes.txt

      - name: Publish release
        if: steps.version-check.outputs.changed == 'true'
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v${{ steps.version-check.outputs.version }}
          release_name: v${{ steps.version-check.outputs.version }}
          body_path: release_notes.txt
