name: run-tests

on:
  push:
  pull_request:

jobs:
  main:
    runs-on: ubuntu-latest

    steps:
      - name: Fetch codebase
        uses: actions/checkout@v4

      - name: Install dependencies
        run: yarn install

      - name: Run tests
        run: echo "TODO - Add tests"
